collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8531915
  brandStrength: 0
  lightness: 0
  brandColors:
    - '#000000'
    - '#D5EFFF'
    - '#C90037'
    - '#A38E4E'
    - '#AED041'
  rhythmicContrast: 0.5926926
typography_spectrum: 0.1595745
layout_spectrum: 0
name: Republicof1/blog
